export const MASTER_SKILL_SET = [
  'python',
  'java',
  'c',
  'c++',
  'c#',
  'javascript',
  'typescript',
  'go',
  'golang',
  'rust',
  'ruby',
  'php',
  'kotlin',
  'swift',
  'r',
  'matlab',
  'scala',
  'perl',
  'bash',
  'machine learning',
  'deep learning',
  'artificial intelligence',
  'data science',
  'data analysis',
  'statistical analysis',
  'supervised learning',
  'unsupervised learning',
  'reinforcement learning',
  'feature engineering',
  'model evaluation',
  'hyperparameter tuning',
  'natural language processing',
  'nlp',
  'text classification',
  'sentiment analysis',
  'named entity recognition',
  'transformers',
  'bert',
  'gpt',
  'large language models',
  'llm',
  'prompt engineering',
  'rag',
  'information retrieval',
  'semantic search',
  'computer vision',
  'image processing',
  'object detection',
  'image classification',
  'segmentation',
  'opencv',
  'mediapipe',
  'yolo',
  'yolov8',
  'pose estimation',
  'optical flow',
  'feature extraction',
  'tensorflow',
  'keras',
  'pytorch',
  'scikit-learn',
  'xgboost',
  'lightgbm',
  'catboost',
  'hugging face',
  'transformers library',
  'numpy',
  'pandas',
  'scipy',
  'matplotlib',
  'seaborn',
  'plotly',
  'cufflinks',
  'statsmodels',
  'sql',
  'mysql',
  'postgresql',
  'sqlite',
  'mongodb',
  'dynamodb',
  'redis',
  'cassandra',
  'elasticsearch',
  'aws',
  'ec2',
  's3',
  'lambda',
  'ecs',
  'eks',
  'gcp',
  'azure',
  'docker',
  'kubernetes',
  'terraform',
  'ci/cd',
  'github actions',
  'jenkins',
  'rest api',
  'graphql',
  'fastapi',
  'flask',
  'django',
  'gin',
  'fiber',
  'node.js',
  'express',
  'microservices',
  'react',
  'next.js',
  'vue',
  'angular',
  'react native',
  'flutter',
  'html',
  'css',
  'tailwind css',
  'bootstrap',
  'data structures',
  'algorithms',
  'object oriented programming',
  'oop',
  'system design',
  'design patterns',
  'operating systems',
  'computer networks',
  'dbms',
  'software engineering',
  'git',
  'github',
  'gitlab',
  'linux',
  'unix',
  'jupyter',
  'notebook',
  'hugging face spaces',
  'gradio',
  'streamlit',
];
